before_script:
  - bundle install --path vendor/bundle

stages:
  - build
  - deploy

build:
  stage: build
  script: bundle exec rake build
  tags:
    - jekyll

deply:
  stage: deploy
  script:
    - bundle exec rake build
    - bundle exec rake deploy
  only:
    - master
  tags:
    - jekyll
