static_path: https://d1238u3jnb0njy.cloudfront.net
styles_path: https://d1238u3jnb0njy.cloudfront.net
scripts_path: https://d1238u3jnb0njy.cloudfront.net

assets:
  debug: false
  baseurl: https://d1238u3jnb0njy.cloudfront.net