safe: false
port: 4000
highlighter: rouge
future: false
timezone: Europe/London
lsi: false
markdown: redcarpet

permalink: /:categories/:year/:month/:title
url: http://localhost:4000
name: Daniel Groves
description: "Photographer, Adventurer, and Developer who is addicted to the mountains."
email: "hello@danielgroves.net"

opengraph:
  page: https://www.facebook.com/danielgrovesphotography
  personal: https://www.facebook.com/profile.php?id=1530170880
  image: /assets/camera-roll/2015/04/20150411-DSC_5263-Edit.jpg

static_path: '/assets'
styles_path: '/styles'
scripts_path: '/scripts'

jekyll-archives:
  layouts:
    tag: tag
  enabled:
    - tags
  permalinks:
    tag: /tag/:name/

paginate: 12

# Disables the default paginator from working
# Otherwise it generates /page2, /page3, etc
# Will find a better fix when time presents itself
paginate_path: ""

exclude: ['Rakefile', 'Gemfile', 'Gemfile.lock', 'readme.md']

redcarpet:
  extensions: []

gems: ["bourbon", "neat", "jekyll-assets", "jekyll-archives", "jekyll-sitemap", "rouge"]

assets:
  sources:
    - _scripts
    - _styles
  js_compressor: uglifier
  css_compressor: sass
  debug: false

defaults:
  - scope:
      path: ""
    values:
      footer_related_posts: true
      comments: false

  - scope:
      path: ""
      type: "pages"
    values:
      layout: "stark"

  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      banner_position: "middle"

mapbox:
  options:
    zoompan: true
    zoomwheel: false
    geocoder: false
    link: false
  id_prefix: danielsgroves.
  access_token: pk.eyJ1IjoiZGFuaWVsc2dyb3ZlcyIsImEiOiJwSlNBVXcwIn0._PdzYUw29IfgzxbOFul2kg
