safe: false
port: 4000
pygments: true
future: false
lsi: false
markdown: redcarpet

permalink: /notebook/:year/:month/:title
pagination: 6
url: http://danielgroves.net
name: Daniel Groves

redcarpet:
  extensions: []
  
sitemap:
    file: /sitemap.xml
    exclude:
        - /feed/index.xml
        - /contact/sent.html
    include_posts:
        - /index.html
        - /notebook/index.md
    change_frequency_name: "change_frequency"
    priority_name: "priority"