safe: false
port: 4000
highlighter: 'pygments'
future: false
timezone: Europe/London
lsi: false
markdown: redcarpet

permalink: /:categories/:year/:month/:title
url: https://danielgroves.net
name: Daniel Groves
description: "Developer and photographer based in southwest england who is addicted to the mountains."
email: "hello@danielgroves.net"

static_path: '/assets'
styles_path: '/styles'
scripts_path: '/scripts'

paginate: 12

# Disables the default paginator from working
# Otherwise it generates /page2, /page3, etc
# Will find a better fix when time presents itself
paginate_path: ""

exclude: ['Rakefile', 'Gemfile', 'Gemfile.lock']

redcarpet:
  extensions: []

sitemap:
    file: /sitemap.xml
    exclude:
        - /feed/index.xml
        - /404.html
        - /page*
        - /Gemfile
        - /Gemfile.lock
        - /Rakefile
    include_posts:
        - /index.html
        - /notebook/index.html
    change_frequency_name: "change_frequency"
    priority_name: "priority"

instagram:
    user_id: 1358824988
    min_timestamp: 2015-01-01T00:00:00+00:00
    max_timestamp: 2015-12-31T11:59:59+00:00

gems: ["bourbon", "neat"]

sass:
  style: :expanded

defaults:
  - scope:
      path: ""
    values:
      footer_related_posts: true
      comments: false

  - scope:
      path: ""
      type: "pages"
    values:
      layout: "stark"

  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
