safe: false
port: 4000
pygments: true
future: false
timezone: Europe/London
lsi: false
markdown: redcarpet

permalink: /:categories/:year/:month/:title
url: http://danielgroves.net
name: Daniel Groves

paginate: 20

# Disables the default paginator from working
# Otherwise it generates /page2, /page3, etc
# Will find a better fix when time presents itself
paginate_path: ""

exclude: ['build.sh']

redcarpet:
  extensions: []

sitemap:
    file: /sitemap.xml
    exclude:
        - /feed/index.xml
        - /contact/sent.html
        - /build.sh
        - /404.html
        - /page*
    include_posts:
        - /index.html
        - /notebook/index.html
    change_frequency_name: "change_frequency"
    priority_name: "priority"