safe: false
port: 4000
highlighter: rouge
future: false
timezone: Europe/London
lsi: false
markdown: kramdown

permalink: /:categories/:year/:month/:title
url: http://localhost:4000
name: Daniel Groves
description: 'Photographer, Adventurer, and Developer who is addicted to the mountains.'
email: 'hello@danielgroves.net'

opengraph:
  page: https://www.facebook.com/danielgrovesphotography
  personal: https://www.facebook.com/profile.php?id=1530170880
  image: /assets/camera-roll/2015/04/20150411-DSC_5263-Edit.jpg

static_path: '/assets'
styles_path: '/styles'
scripts_path: '/scripts'

imgix:
  main_images: https://danielgroves-net.imgix.net/
  metadata_images: https://danielgroves-net-2.imgix.net/

jekyll-archives:
  layouts:
    tag: tag
  enabled:
    - tags
  permalinks:
    tag: /tag/:name/

pagination:
  limit: false
  per_page: 12
  permalink: /:num/index.html

exclude:
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - readme.md
  - .gitlab-ci.yml
  - vendor

kramdown:
  parse_span_html: false
  parse_block_html: false

gems:
  - bourbon
  - neat
  - jekyll-assets
  - jekyll-archives
  - jekyll-sitemap
  - rouge
  - jekyll-redirect-from
  - octopress-paginate

assets:
  sources:
    - _scripts
    - _styles
  js_compressor: yui
  css_compressor: yui
  debug: false

defaults:
  - scope:
      path: ''
    values:
      footer_related_posts: true
      comments: false

  - scope:
      path: ''
      type: 'pages'
    values:
      layout: 'stark'
      is_page: true
      is_post: false

  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'default'
      banner_position: 'middle'
      is_page: false
      is_post: true

mapbox:
  options:
    zoompan: true
    zoomwheel: false
    geocoder: false
    link: false
  id_prefix: danielsgroves.
  access_token: pk.eyJ1IjoiZGFuaWVsc2dyb3ZlcyIsImEiOiJwSlNBVXcwIn0._PdzYUw29IfgzxbOFul2kg
