safe: false
port: 4000
highlighter: 'pygments'
future: false
timezone: Europe/London
lsi: false
markdown: redcarpet

permalink: /:categories/:year/:month/:title
url: https://danielgroves.net
name: Daniel Groves

paginate: 12

# Disables the default paginator from working
# Otherwise it generates /page2, /page3, etc
# Will find a better fix when time presents itself
paginate_path: ""

exclude: ['build.sh', 'Rakefile', 'Gemfile', 'Gemfile.lock', 'Pipfile']

redcarpet:
  extensions: []

sitemap:
    file: /sitemap.xml
    exclude:
        - /feed/index.xml
        - /contact/sent.html
        - /build.sh
        - /404.html
        - /page*
    include_posts:
        - /index.html
        - /notebook/index.html
    change_frequency_name: "change_frequency"
    priority_name: "priority"

hire_me: false

instagram:
    client_id: "43ded072c3454f5ba4b02f1c4ff19e29"
    client_secret: "de4ea68d56f14be583e4bad8314eaf50"
    user_id: 1358824988
